### ISSUE TITLE
 helhum / dotenv-connector  only work with "symfony/dotenv": "v5.3.0"

### ISSUE THREAD

**Issue by fritzdacat** [helhum/dotenv-connector#37] opened 2021-07-28 21:26 UTC
When I do a composer update with TYPO3 10.4.18 I get these errors:

Fatal error: Uncaught Error: Call to undefined function Symfony \ Component \ Dotenv \ str_starts_with () in /Volumes/Webs/toolboxWebs/xxxxxxx/vendor/symfony/dotenv/Dotenv.php:193
Stack trace:
# 0 /Volumes/Webs/toolboxWebs/xxxxxxx/vendor/symfony/dotenv/Dotenv.php(568): Symfony \ Component \ Dotenv \ Dotenv-> populate (Array, false)
# 1 /Volumes/Webs/toolboxWebs/xxxxxxx/vendor/symfony/dotenv/Dotenv.php(92): Symfony \ Component \ Dotenv \ Dotenv-> doLoad (false, array)
# 2 /Volumes/Webs/toolboxWebs/xxxxxxx/vendor/helhum/dotenv-connector/src/Adapter/SymfonyDotEnv.php(15): Symfony \ Component \ Dotenv \ Dotenv-> load ('/ Volumes / Webs / t ... ')
# 3 /Volumes/Webs/toolboxWebs/xxxxxxx/vendor/helhum/dotenv-include.php(4): Helhum \ DotEnvConnector \ Adapter \ SymfonyDotEnv-> exposeToEnvironment ('/ Volumes / Webs / t ...' )
# 4 /Volumes/Webs/toolboxWebs/xxxxxxx/vendor/helhum/dotenv-include.php(5): Helhum \ DotEnvConnector \ IncludeFile :: {closure} ('/ Volumes / Webs / t ...' )
# 5 / Volumes / Webs / toolboxWebs / xxxxxxx / vendor / helhum / dotenv-connector in /Volumes/Webs/toolboxWebs/xxxxxxx/vendor/symfony/dotenv/Dotenv.php on line 193

If I specify in composer.json that "symfony / dotenv": "v5.3.0" should be used, a composer update runs ...

**Comment by helhum** [comment] 2021-07-28 23:38
Duplicate of #36

**Closed by helhum** 2021-07-28 23:38 UTC
